# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.18.3"
 
default_platform :ios
 
platform :ios do
 
  # 1
  desc "Creating a code signing certificate and provisioning profile"
  # 2
  lane :provision do
    # 3
    cocoapods
    produce(
      app_name: ‘Mark Breakdown’,
      language: 'English',
      app_version: '1.0',
      sku: ‘123’
    )
    # 4
    cert
    # 5
    sigh(force: true, development: true)
  end
 
  error do |lane, exception|
  # This block is called if there was an error running a lane.
  end
 
end